// <auto-generated />
namespace MusicApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class NewColumn_Songs_ArtistName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewColumn_Songs_ArtistName));
        
        string IMigrationMetadata.Id
        {
            get { return "202101081909240_NewColumn_Songs_ArtistName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
