// <auto-generated />
namespace MusicApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class DropColumn_Albums_SongsNumber : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DropColumn_Albums_SongsNumber));
        
        string IMigrationMetadata.Id
        {
            get { return "202101132345461_DropColumn_Albums_SongsNumber"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
